Test,webhello/test-hello-server: More detailed trap ERR output
We now include the filename as well ($0) so that we can see which
script was failing, as Test calls webhello/test-hello-server.
We also expand it to three lines (head, file, command) so that
it's easier to read.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
-trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
-      exit $ec;' ERR
+trap '
+    ec=$?
+    echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO"
+    echo 1>&2 "    file=$0"
+    echo 1>&2 "    cmd=$BASH_COMMAND"
+    exit $ec;
+' ERR
 
 elapsed_start=$(date +%s)
 
