package/make-package: Shorten internal error handling code
We no longer run this from inside other scripts, and so don't need
so much information (e.g., the filename) on internal errors.

diff --git a/package/make-package b/package/make-package
--- a/package/make-package
+++ b/package/make-package
@@ -1,12 +1,6 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
-trap '
-    ec=$?
-    echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO"
-    echo 1>&2 "    file=$0"
-    echo 1>&2 "    cmd=$BASH_COMMAND"
-    exit $ec;
-' ERR
+trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO"; exit $ec' ERR
 
 export PROJDIR=$(command cd "$(dirname "$0")/.." && pwd -P)
 mkdir -p "$PROJDIR"/.build/package
